defaults:
  - paths: paths
  - data_processor: processor
  - model: arf #gaussian_copula
  - inference: inference_runner
  - imputation: histogram_imputation
  - _self_

run_training: true
run_inference: true
run_evaluation: true

event: no_event

experiment_name: restart

run_name: NE

sampled_patients_num: 200
non_zero_threshold: 20.0
ml_flow_tracking_uri: http://10.100.111.210:5004
primary_key: ${data_processor.id_column}

