defaults:
  - paths: paths
  - data_processor: processor
  - model: gaussian_copula
  - inference: inference_runner
  - _self_

run_training: true
run_inference: true

event: no_event

experiment_name: PublicRepoTest2
run_name: NE

sampled_patients_num: 100
non_zero_threshold: 90.0
ml_flow_tracking_uri: http://10.100.111.210:5006
primary_key: idAuswertung

